[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]
nixLibs = ["openssl"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "export DATABASE_URL=${DATABASE_URL:-postgresql://user:pass@localhost:5432/db}",
  "npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && npm start"
